#cloud-config
packages:
  - fail2ban
  - unattended-upgrades
  - ntpdate

timezone: ${TimeZone}

ntp:
  enabled: true
  servers:
    - 0.au.pool.ntp.org
    - 1.au.pool.ntp.org
    - 2.au.pool.ntp.org
    - 3.au.pool.ntp.org

users:
  - name: ${AuthorizedUserName}
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ${AuthorizedUserSSHKey}

write_files:
  - path: /etc/update-motd.d/99-unauthorised-access
    permissions: "0755"
    owner: "root"
    content: |
      echo 'UNAUTHORIZED ACCESS TO THIS DEVICE IS PROHIBITED

      You must have explicit, authorized permission to access or configure this device. Unauthorized attempts and
      actions to access or use this system may result in civil and/or criminal penalties. All activities performed on
      this device are logged and monitored.'

runcmd:
  # SSH
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  #  - sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - "printf '\nClientAliveInterval 100\nClientAliveCountMax 0' >> /etc/ssh/sshd_config"
  - service ssh restart

power_state:
  timeout: 120
  delay: "${ShutdownDelay}"
  message: System will shutdown in ${ShutdownDelay} minutes
  mode: poweroff
